### ISSUE TITLE
i3-10100 Processor Graphics Graphics Max Dynamic Frequency

### ISSUE THREAD

**Issue by woondeewyy** [xiaoka-li/Hackintosh-CVN-B460i-10100#1]
i3 10100 核显最大频率 1.10 GHz。哈哈。
看这个链接：https://ark.intel.com/content/www/us/en/ark/products/199283/intel-core-i3-10100-processor-6m-cache-up-to-4-30-ghz.html

**Comment by XiaoKaByte** [comment]
感谢分享，之前没有去看硬件的参数🤦‍♂️
