### ISSUE TITLE
bios需要怎么设置呢

### ISSUE THREAD

**Issue by bbmeme05** [xiaoka-li/Hackintosh-CVN-B460i-10100#2]
我的是B460M gaming pro应该和你的差不多,照着OC文档配置的EFI然后报错,请教了别人是cfglock的原因.你的主板解锁了吗

**Comment by XiaoKaByte** [comment]
我的bois没有cfg解锁选项，我也没有去刷
关闭config里的AppleXcpmCfgLock 、AppleCpuPmCfgLock
主板调节选项不多，我就关闭了cms，其他的好像没有关，
根据报错信息去找答案，网上教程还挺多的，可以看看bilibili，
一点点完善应该就可以了

**Comment by bbmeme05** [comment]
收到,谢谢
